<!doctype html>
<html>
<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <title>Напоминания</title>
    <link rel="stylesheet" href="/../remi/view/css/styles.css" type="text/css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.3/moment-with-locales.min.js"  integrity="sha512-vFABRuf5oGUaztndx4KoAEUVQnOvAIFs59y4tO0DILGWhQiFnFHiR+ZJfxLDyJlXgeut9Z07Svuvm+1Jv89w5g==" crossorigin="anonymous" referrerpolicy="no-referrer"> </script>
</head>
<body class="body">
    <div class="pop-up-container"></div>
    
    <section class="pop-up">
        <span class="close">x</span>
        
        
        <div class="form_container">
            <form class="form" name="addForm">
                <div name="id"></div>
                <textarea class="form__textarea" name="text" placeholder="Введите текст напоминания..."></textarea>
                <div class="form__block">
                    <div class="form__date_time">
                        <input class="form__el" type="date" name="date">
                        <input class="form__el" type="time" name="time">
                    </div>
                    <select class="form__el" name="period">
                        <option value="">Повторять</option>
                        <option value="0">Никогда</option>
                        <option value="3600">Каждый час</option>
                        <option value="86400">Каждый день</option>
                        <option value="604800">Каждую неделю</option>
                    </select>
                    <input class="form__el submit_create" type="submit">
                </div>
            </form>
        </div>
 

    </section>
    
    <header class="header">
        <h1 class="header__h1">Напоминания</h1>
    </header>
        
    <div class="wrapper">
        <section class="listOfReminders" id="message">
            <?php reminderService()?>
        </section>
    </div>

    <footer class="footer">
        
    </footer>

</body>
</html>